import Head from "next/head";
import { useSession, signOut } from "next-auth/react"
import LoginPage from "@/components/LoginPage";
import Nav from "@/components/Nav";

export default function Layout({ children }) {
    const { data: session } = useSession()

    if (!session) {
        return <LoginPage />
    }

    return (
        <>
            <Head>
                <title>Limeshop</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-blue-900 min-h-screen flex">
                <Nav />
                <div className="bg-white flex-grow mt-2 mr-2 rounded-lg p-4 mb-2">
                    {children}

                    <div className="mt-10 border-t-2 pt-2">
                        <button onClick={signOut}>Logout</button>
                    </div>
                </div>
            </div>
        </>
    );
}
