import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Limeshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-blue-900 w-screen h-screen flex items-center">
        <div className="text-center w-full">
          {session ? (
            <>
              Signed in as {session.user.email} <br />
              <button onClick={() => signOut()}>Sign out</button>
            </>
          ) : (
            <>
              <button
                className="bg-white py-2 px-4 rounded-lg"
                onClick={() => signIn('google')}
              >Login with Google</button>
            </>
          )}

        </div>
      </div>
    </>
  );
}
